### ISSUE TITLE
The result of benchmark models on CUB dataset

### ISSUE THREAD

**Issue by buptxiaofeng** [WenbinLee/DN4#16]
There is a paper published on ICLR 2019 https://arxiv.org/pdf/1904.04232.pdf. In this paper, they also evaluate the performance of protonet on the CUB dataset and  their result is far better than the result reported in this paper. So I am wondering how the result is obtained in this paper?

**Comment by WenbinLee** [comment]
Hi, I think there are two reasons that make the results different. The first is that we use the CUB-200-2010 dataset which is much smaller than the CUB-200-2011 dataset used in the ICLR19 paper. The second is that we don't use any tricks (e.g., data augmentation) for training the models, while that paper has used the data augmentation trick. Thanks.

**Comment by WenbinLee** [comment]
So our implementation of ProtoNet will easily suffer from the overfitting problem because of using a much smaller dataset without any training tricks. I recommend that you can use the CUB-200-2011 dataset instead of the CUB-200-2010 dataset and employ some deep learning training tricks under a fair comparison setting.

**Comment by buptxiaofeng** [comment]
Thanks for your clarification.
