### ISSUE TITLE
batch_size只能设为1？

### ISSUE THREAD

**Issue by lailvlong** [WenbinLee/DN4#7]
你好，请问这个代码只支持batch_size=1吗？我看了和运行了DN4_Train_5way5shot.py文件，发现把batch_size设为2时，会把2个episode的support set、query set糅合在一起，就是episode1中的support set 的 class 0 和 episode2 中的support set 的class 0的样本会当成是同一个class 0，相当于class 0变成了10 shot，但这10个样本实际来自2个不同的类。

**Comment by WenbinLee** [comment]
是的，目前代码只支持batchsize 为1。如果想实现batchsize 大于1，可能有两种简单替代方案，一是采用多GPU, 另外就是可以让梯度晚一些回传。我后面如果有时间可以再尝试实现一个可以任意设置batchsize 的版本。谢谢。



    


            在2019年06月17日 04:23，lailvlong 写道： 你好，请问这个代码只支持batch_size=1吗？我看了和运行了DN4_Train_5way5shot.py文件，发现把batch_size设为2时，会把2个episode的support set、query set糅合在一起，就是episode1中的support set 的 class 0 和 episode2 中的support set 的class 0的样本会当成是同一个class 0，相当于class 0变成了10 shot，但这10个样本实际来自2个不同的类。



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/WenbinLee/DN4/issues/7?email_source=notifications\u0026email_token=AE3GGHHU3HD6WDBYJTMLI73P25X4ZA5CNFSM4HYVVOU2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GZ3OYCA",

"url": "https://github.com/WenbinLee/DN4/issues/7?email_source=notifications\u0026email_token=AE3GGHHU3HD6WDBYJTMLI73P25X4ZA5CNFSM4HYVVOU2YY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GZ3OYCA",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
