### ISSUE TITLE
about ablation study

### ISSUE THREAD

**Issue by valencebond** [WenbinLee/DN4#8]
thanks for your detailed code. I am not sure about the settings of DN4-IoI2 in paper 4.6. As the paper said, 
> DN4-IoI-2 restricts the search for the k-NN of a query’s local descriptor within each individual support image

in 5way5shot, if i understand right,  lol-2 select top k local descriptors from **one image pool** instead from **one class pool** (as DN4 settings) for a query local descriptor, so there are 5 times(5 shot) local descriptors selected, then sum 5 times similarities for one query local descriptor. If I miss sth, please help me figure it out.

**Comment by WenbinLee** [comment]
Sorry for the late response. Because DN4-IoI-2 is an image-to-image variant, we first calculate an image-to-image similarity (based on local descriptors) between a query image and each support image in the same class. When we calculate this image-to-image similarity (as same as the 1shot setting with DN4), we search k local descriptors for each query local descriptor. After we obtain 5 similarities between this query image and one class (5 support images), we select k-nearest neighbors in the image level for each query image and sum these similarities.  Then we can get the final unique similarity.
If you have any questions, please let me know. Thank you.
